# Generated by Django 6.0.2 on 2026-02-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_dochistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dochistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
